[[redirects]]
  from = "https://qro.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.qro.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://queretaro.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.queretaro.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.xn--quertaro-e1a.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://omm-queretaro-blog.netlify.com/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://ommqro.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.ommqro.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true
# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "public/"

  # Default build command.
  command = "gatsby build"
