[[redirects]]
  from = "https://qro.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.qro.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://queretaro.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.queretaro.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.xn--quertaro-e1a.omm.mx/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://omm-queretaro-blog.netlify.com/*"
  to = "https://xn--quertaro-e1a.omm.mx/:splat"
  status = 301
  force = true
